FROM node:22
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="career-sathi-bot.firebaseapp.com"
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID="career-sathi-bot"
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="career-sathi-bot.firebasestorage.app"
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="131929273763"
ENV NEXT_PUBLIC_FIREBASE_APP_ID="1:131929273763:web:ca5f609564cbb8b0169616"
ENV NEXT_PUBLIC_FIREBASE_API_KEY= "AIzaSyAG4_a-soOgFq5Hk7yMmiVbeHSSxVdpkmc"
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-M958F5SJH6"
RUN npx prisma generate
RUN npm run build
EXPOSE 8080
ENV PORT 8080
CMD ["npm", "start"]
